---
# Experiment configuration
total_epochs: 2
epochs_per_cycle: 1
wait_for_clients: true
net: Cifar100AlexNet
dataset: cifar100
# Use cuda is available; setting to false will force CPU
cuda: true
experiment_prefix: "cifar_100_alexnet"
output_location: "output"
tensor_board_active: true
clients_per_round: 1
system:
  federator:
    hostname: "localhost"
    nic: "lo"
  clients:
    amount: 1
