---
# Experiment configuration
total_epochs: 10
epochs_per_cycle: 1
wait_for_clients: true
net: Cifar10CNN
dataset: cifar10
# Use cuda is available; setting to false will force CPU
cuda: true
experiment_prefix: "ex-gcp-c20"
output_location: "output"
tensor_board_active: true
clients_per_round: 5
system:
  federator:
    hostname: "192.168.1.183"
    nic: "wlo1"
  clients:
    amount: 10
